name: Car Rental System CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore CarRentalManagementSystem.slnx

      - name: Build Solution
        run: msbuild CarRentalManagementSystem.slnx /p:Configuration=Release
