name: Car Rental System CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore CarRentalManagementSystem.slnx

      - name: Build Solution
        run: msbuild CarRentalManagementSystem.slnx /p:Configuration=Release

      - name: Install Test Platform
        run: nuget install Microsoft.TestPlatform -Version 17.11.1 -OutputDirectory testrunner

      - name: Run Tests
        shell: powershell
        run: |
          $vstest = Get-ChildItem -Path "testrunner" -Recurse -Filter "vstest.console.exe" | Select-Object -First 1
          & $vstest.FullName "**\bin\Release\*Tests.dll"
